apiVersion: v1
kind: Service
metadata:
  name: triplan-peototype
spec:
  ports:
  - port: 80
    targetPort: prototype-port
    protocol: TCP
  selector:
    k8s-app: triplan-prototype
  type: ClusterIP
